### ISSUE TITLE
IE8 not supported ?

### ISSUE THREAD

**Issue by MonsterKim** [gromo/jquery.scrollbar#100]
Hi , Is there anything problems with the plugin ?
I'm using firefox and chrome , and it runs very well . but when I'm trying it in IE8 , the browser is no response and must be shut down .

**Comment by gromo** [comment]
Did you have the same problem with demo pages? If no, check your CSS styles - IE8 is very bad with max-height. Look at documentation page - section Browser support

> Browser support: IE7+, Edge, Firefox, Opera, Chrome, Safari
> 
> Of course all modern browsers are supported starting from IE7. The most problematic browser is IE, as you already suspect. But it's not IE7, it's IE8! Surprised? I was! IE7 works better with height/width calculations than IE8. IE8 renderer is crashed when using max-height with overflow:auto. It is officially logged as a bug in the final version of IE8 with no fix. There are also other bugs with max-height/max-width and positioning. So, be careful if you are going to support IE8.
