### ISSUE TITLE
Scrollbar is not a function

### ISSUE THREAD

**Issue by ErraticFox** [gromo/jquery.scrollbar#102]
Hello, I'm building a app in Node.Js with Electron, I couldn't get it working in there. So I brought a example to CodePen and used the CDNs for the library (both the min css and min js) along with jQuery but I keep getting the error `$(...).scrollbar is not a function`, why is this? Thanks in advance.

Here's the pen: http://codepen.io/ErraticFox/pen/JKqYdq

**Comment by gromo** [comment]
You didn't set CSS height/max-height for you scrollbar container

**Comment by ErraticFox** [comment]
I updated it, it seems to work a bit but I don't see the scroll bar. Sorry, I'm kinda new to this stuff. 😞

**Comment by gromo** [comment]
add max-height via class to your container

**Comment by ErraticFox** [comment]
I'm confused, the CSS in the CodePen is the exact same as your first Basic Demo. Shouldn't that include the CSS for the height and max-height for the scrollbar container?

**Comment by ErraticFox** [comment]
Finally got it to work, thanks for the plugin!
