### ISSUE TITLE
'destroy' method throws error

### ISSUE THREAD

**Issue by inliner** [gromo/jquery.scrollbar#103]
'destroy' method throws error - andSelf is not a function. 
Lines 132, 133:

    this.scrollx.scroll.removeClass('scroll-scrollx_visible').find('div').andSelf().off(this.namespace);
    this.scrolly.scroll.removeClass('scroll-scrolly_visible').find('div').andSelf().off(this.namespace);

andSelf is not declared anywhere. Please take a look.

**Comment by gromo** [comment]
Deprecated in jQuery, fixed
