### ISSUE TITLE
Add options to disable horizontal and/or vertical scrolling

### ISSUE THREAD

**Issue by JonGarbayo** [gromo/jquery.scrollbar#108]
Hi,

Could you add two options to disable horizontal and/or vertical scrolling?

It could be like:

``` js
$('.scroll').scrollbar(
    enableScrollX: false
    enableScrollY: true
);
```

with `true` and `true` as default settings.

Because some techniques provided by CSS Tricks here : https://css-tricks.com/full-browser-width-bars and [this](https://css-tricks.com/full-browser-width-bars/#article-header-id-0) in particular need the horizontal scrolling to be disabled.

Thanks for reading!

**Comment by gromo** [comment]
I belive you can do this via CSS, but you will have to use !important to override applied scrollbar styles

**Comment by JonGarbayo** [comment]
Yes, it's already done, and works very well in desktop browsers. But on mobile, you can scroll horizontally anyway. I think it's because of touch events via Javascript (I'm not really aware of this kind of events though, sorry).

**Comment by gromo** [comment]
I believe that custom scrollbar should not handle touch events in js (if you do not use disableBodyScroll, which I do not recommend). Try to set `ignoreMobile: true` and check if native scroll behavior is the same.

**Comment by JonGarbayo** [comment]
`ignoreMobile: true` was already set. I'm investigating on this phenomenon.
This week-end, I hope I will have the time to post a jsFiddle, to recreate the problem.

**Comment by JonGarbayo** [comment]
Up.

**Comment by gromo** [comment]
If option ignoreMobile is set to true, than you deal with native browser scrollbars, not JS emulation (custom scrollbar won't be initialized at all). So CSS is the thing you need.
