### ISSUE TITLE
When we use in Multi-select Horizontal scroll issue not working 

### ISSUE THREAD

**Issue by baladkb** [gromo/jquery.scrollbar#114]
Hi @gromo We have using Your Library and thanks it's use full for us 👍 and we tried to use Our scrollbar plugin in multi select select tag, it's working fine but horizontal scroll not working, if You have any updates please help us.
```
<select multiple="multiple" class="scrollbar-inner">
<option >Data</option>
...
</select>
```

**Comment by gromo** [comment]
Hi @baladkb 

Initially custom scrollbar was designed to work with block elements, not select. I'm not sure I can help with this case. What do you think about using custom select too?
