### ISSUE TITLE
demo example not working when replicated. (Microsoft windows vista)

### ISSUE THREAD

**Issue by amit1702** [gromo/jquery.scrollbar#115]
I have tried replicating the first example of http://gromo.github.io/jquery.scrollbar/demo/advanced.html
my ie11 scrollbar disapppears but i do not get new scrollbar. 

i think we need some improvement in the demo code. Please do if required.

i could successfully replicate the 2nd example. (externel)

**Comment by gromo** [comment]
Have you downloaded images sprite for scrollbar?

**Comment by amit1702** [comment]
Hi gromo. Thanks for response. I was on leave for two days so sorry for delay. Please have a  a look and let me know if i am doing something wrong. I have tried to replicate first example of http://gromo.github.io/jquery.scrollbar/demo/advanced.html

https://jsfiddle.net/amiku1702/1om4epy0/3/

Regards

**Comment by amit1702** [comment]
Hi @gromo i tried your solution and it worked. Thanks.

**Comment by gromo** [comment]
Unfortunately I don't have time to dig into angular-ui-grid js code to find out how it builds content, but it can be tricky to modify it to use custom scrollbar.

**Comment by amit1702** [comment]
Hi @Gromo. Ok. Thanks.
