### ISSUE TITLE
blinking horizontal scrollbar

### ISSUE THREAD

**Issue by pemich** [gromo/jquery.scrollbar#116]
Hi,

I am trying to use your jquery scrollbar, everything is perfect, but horizontal scrollbar is blinking in browsers like Firefox, IE when div appears // one element hides and another shows by jquery.
I tried to use fix from k-one-o-two but it did not work.

So my question is: how to fix this problem? 
Thank you for your time and answer.

**Comment by gromo** [comment]
I believe it happens because of timer-based size checks. So you have to get custom scrollbar instance and call init() method manually right after hiding/showing content.
