### ISSUE TITLE
[Chrome] Scrollbar stop just few pixel before end

### ISSUE THREAD

**Issue by Philigane** [gromo/jquery.scrollbar#119]
Hi,

I've search for a while but i don't understand why. When i use your plugin (on chrome, on firefox it works) and i scroll top or left everything is fine. But if i scroll right or down the scroll stop and i can't see what is written.

```
/**
 * jQuery CSS Customizable Scrollbar
 *
 * Copyright 2014, Yuriy Khabarov
 * Dual licensed under the MIT or GPL Version 2 licenses.
 *
 * If you found bug, please contact me via email <13real008@gmail.com>
 *http://gromo.github.io/jquery.scrollbar/demo/basic.html
 * @author Yuriy Khabarov aka Gromo
 * @version 0.2.4
 * @url https://github.com/gromo/jquery.scrollbar/
 *
 */
```

![sans titre](https://cloud.githubusercontent.com/assets/14936772/21548924/65159e5a-cdef-11e6-9f59-bdaf50bd7c52.png)

Why ?

Regards

**Comment by gromo** [comment]
Hi,

This is the question I cannot answer without example with bug. Does this bug exist on basic / advanced demo pages?

**Comment by Philigane** [comment]
Hi,

Thank you for reply. Unfortunately i cannot give you anything for showing the bug. This bug does not happen on basic and advanced demo pages but i was hopping you already saw a bug like that.

**Comment by Philigane** [comment]
I just upgrade my plugin version and the bug flies away. Thanks anyway
