### ISSUE TITLE
Does not work in Firefox on MacOs

### ISSUE THREAD

**Issue by kerygmafabian** [gromo/jquery.scrollbar#122]
None of the examples works in FF on MacOS.
Any idea how to fix this?

Thanks and best regards
Fabian

**Comment by gromo** [comment]
Too hard to implement, so FF on Mac OS is ignored

**Comment by sulym-roman** [comment]
It's a great plugin and I hope you will consider fixing this issue in the near future :)

**Comment by gromo** [comment]
Thank you, as soon as I will have free time to update it :)
