### ISSUE TITLE
scrollbar doesn't work when setting height not using class

### ISSUE THREAD

**Issue by tingyuming** [gromo/jquery.scrollbar#123]
```HTML
<style type="text/css">
        #test {
            height: 50px;
            overflow: hidden;
        }
</style>

<div class="demo">
    <div id="test" class="scrollbar-inner">
        <p class="permanent">
            Simple outer scrollbar can be used as CSS base for custom outer scrollbars.
            This example shows nested scrollbars functionality: nested scrollbar styles do not
            interfere with parent scrollbar styles, i.e. different scrollbars can be safely used
            inside each other.
        </p>
    </div>
</div>
```

The new version of scrollbar 0.2.11 doesn't work if I set the height not using class, like ID in the example. I find a way to fix this issue is set the height to empty of cssOptions.
``` JS
cssOptions = {
    "height": "",
    "margin-bottom": browser.scroll.height * -1 + 'px',
    "max-height": ""
};
```
It worked well before version 0.2.8.

**Comment by gromo** [comment]
Set height/max-height using CSS classes, not IDs, because custom scrollbar duplicate element, and ID should be unique per page.

**Comment by tingyuming** [comment]
@gromo 
the same issue with HTML tags like fieldset. Is it possible to fix this issue not using a class?

**Comment by gromo** [comment]
Why not CSS classes? They are designed to be used for this purpose. Add new additional unique class to your container and that's all.

**Comment by tingyuming** [comment]
@gromo Much appreciated.
I think it would be better to add this: only using unique class to control the height to document.
Thanks a lot.
