### ISSUE TITLE
How to control when scrollbar should appear

### ISSUE THREAD

**Issue by pavlito** [gromo/jquery.scrollbar#124]
Hi Gromo,

I am looking for an option, to control height.

I have panel which has some list items, and i want to activate scrollbar if height of panel is >600px, othervise it should not applied.

I am trying with fixed height, but problem occurs when that panel have small number of items or nothing at all, blank space remain because of height 600px

Any way to solve that.

**Comment by gromo** [comment]
Why not use max-height?

**Comment by pavlito** [comment]
I have tried that, but he calculates it own.

I tried with
`.scroll-content {
max-height:600px;
}` and with

`.scrollbar-inner {
max-height:600px;
}` 


But he calulates height of 557px?

**Comment by gromo** [comment]
Look at http://gromo.github.io/jquery.scrollbar/demo/basic.html - you can add/remove content by buttons and see that height is dynamic - it's limited by max-height

**Comment by pavlito** [comment]
So you set max height on .scroll-wrapper to be 250px. 
And scroll-content (his child element), have the same height, calculated by js. 

I have the same logic on my page, where i set scroll-wrapper to have max-height: 600px, but my scroll-content have 557px also calculated by js

**Scrollbar-wrapper**
![image](https://cloud.githubusercontent.com/assets/3610827/23503951/f26c53f0-ff3d-11e6-918e-b9c40ff4612f.png)

**Scroll-content**
![image](https://cloud.githubusercontent.com/assets/3610827/23503997/1525d592-ff3e-11e6-9c38-4e0b630eeb6c.png)

**Comment by gromo** [comment]
do not touch scrollbar classes, use your own and set max-height to it

**Comment by pavlito** [comment]
Okay will do that. I have noticed that it is not setting properly scrollbar, probably because i use on that items also jquery plugin (chosen.js) for customizing inputs. 

Any suggestions?

**Comment by gromo** [comment]
prepare example on jsFiddle.net with minimum JS/HTML/CSS required for reproducing this issue, and I will try to look at it in next few days

**Comment by pavlito** [comment]
Hi Gromo, i think the issue is fixed.
