### ISSUE TITLE
What am i doing wrong WTF

### ISSUE THREAD

**Issue by fredleput** [gromo/jquery.scrollbar#126]
Hi,
I don't understand....

HTML markup :
```

<div id="scrollable"><p>Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n'a pas fait que survivre cinq siècles, mais s'est aussi adapté à la bureautique informatique, sans que son contenu n'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.</p>
</div>
```
CSS :

```
#scrollable {
		position: relative;
		width: 100%;
		height: 590px;
		overflow: hidden;
}
```

JS (after dom is fully loaded) :

`$('#scrollable').scrollbar();`

Result :

![wtf](https://cloud.githubusercontent.com/assets/3998154/24305897/d90d4d14-10be-11e7-84a8-a442f0711a69.jpg)

any help appreciated...

Fred.

**Comment by gromo** [comment]
do not use IDs for styling, use CSS classes. Also, you forgot one of the srollbar classes - scrollbar-inner, scrollbar-outer, scrollbar-dynamic, etc...

**Comment by xahon** [comment]
I cannot get scrollbar working too. Here is my pen https://codepen.io/anon/pen/WONjvX

**Comment by gromo** [comment]
@xahon I don't see any CSS that limits your .content element's height, also, you init scrollbar on content, which doesn't have scrollbar classes; instead scrollbar class is in INSIDE container. Try to copy HTML/CSS/JS from demo pages
