### ISSUE TITLE
Foundation + Firefox problem with visible native scrollbar

### ISSUE THREAD

**Issue by anephew** [gromo/jquery.scrollbar#127]
Hello!

I'm trying to include jquery.scrollbar in the foundation. The problem is that in Firefox near custom scrollbar appears native scrollbar. Where can be the problem?

![image](https://cloud.githubusercontent.com/assets/551514/24322497/706671ec-1176-11e7-8fac-f0970ecde988.png)

[Here example](http://codepen.io/anephew/pen/EWpPGd)

**Comment by gromo** [comment]
Firefox on Mac?

**Comment by anephew** [comment]
@gromo 

No, Windows 10!

**Comment by gromo** [comment]
I couldn't check, scripts/styles on new.vitroart.ru are not available
