### ISSUE TITLE
Problem with offcanvas sidebar

### ISSUE THREAD

**Issue by pavlito** [gromo/jquery.scrollbar#128]
Hi Gromo,

Great plugin!!!

Currently i am experiencing problem, scrollbar-inner somehow doesnt calculate height.
Check ss
![image](https://cloud.githubusercontent.com/assets/3610827/24351811/85bf012c-12e7-11e7-9919-f3559ae90396.png)

Suggestion?

**Comment by gromo** [comment]
What css do you use? What about native scrollbar - does it behave the same?

**Comment by pavlito** [comment]
I am using bootstrap panel
If I set default overflow:scroll to panel-body -> then same problem.
If i set to panel (whole element) -> it works?

**Comment by pavlito** [comment]
![image](https://cloud.githubusercontent.com/assets/3610827/24352200/eab166c8-12e8-11e7-9aa8-9dbbd7b05f95.png)

If i set height of panel to 95% -> then works..

**Comment by pavlito** [comment]
![image](https://cloud.githubusercontent.com/assets/3610827/24352238/1762de2c-12e9-11e7-976e-dbc295ddd61f.png)
 Activating scrollbar plugin, scrollbar gets stucked :)

**Comment by gromo** [comment]
I think there are some CSS rules that prevent using jquery scrollbar on bootstrap panel/panel-body. Can you wrap your content inside panel-body into custom DIV with height/width you need (configured via CSS class!) and apply custom scrollbar there?
