### ISSUE TITLE
ScrollTop() doesn't run if scrollbar() use for the whole side

### ISSUE THREAD

**Issue by derSteffen** [gromo/jquery.scrollbar#131]
Hello,

if I use scrollbar() as a whole side-wrapper, i can't use scrollTop()-Events to fade div or some other ScrollTop-Action!

My ScrollTop()-Events are before the scrollbar()-Events and libary! If I delete the whole-wrapper-site-scrollbar()-effect, the scrollTop() runs! Other scrollbar()-effects in the side also run perfect, including scrollTop()-Effects ..... only if i have a wrapper around the whole side with scrollbar() it want to be run.

The problem is the
`.wrapper {
    height: 100%;
}`

Do you have any solutions for me?

THANKS

Greetings

**Comment by gromo** [comment]
Try to set min-height: 100% instead of height: 100%, should help

**Comment by derSteffen** [comment]
hello, nothing work ... it works. but not the scrollTo() ... i tried min-height, max-height together with height, I tried height with a pixel-value .. nothing. I tried differnt overflow or position!

**Comment by gromo** [comment]
Can you make an example on jsFiddle.net ?
