### ISSUE TITLE
How to get "scrollTop"?

### ISSUE THREAD

**Issue by sonymaker** [gromo/jquery.scrollbar#135]
"ScrollTop()" doesn't work. It return 0.
Please reply.

$('.scrollbar-outer').scrollbar();
$('.scrollbar-outer').scrollTop(50);
var nScrollTop = $('.scrollbar-outer').scrollTop(); //I want get "scrollTop" value. How can I?

**Comment by gromo** [comment]
jQuery('.scrollbar-outer').not('.scroll-content').scrollTop();

**Comment by sonymaker** [comment]
Thanks. You're my hero! ^^;
