### ISSUE TITLE
Scrollbar Issue with Firefox browser, works perfectly in Chrome

### ISSUE THREAD

**Issue by warlockdn** [gromo/jquery.scrollbar#138]
Hi,

Please find the jsfiddle 

[https://jsfiddle.net/warlockdn/Ld4qa4Lz/](https://jsfiddle.net/warlockdn/Ld4qa4Lz/)

The scrollbar shows perfectly in chrome but firefox shows both scroll vertical and horizontal and an extra height. Can you please check and suggest what's wrong and how can it be fixed. Thanks.

**Comment by gromo** [comment]
Hi, do you test firefox on Mac?

**Comment by warlockdn** [comment]
no I am on a windows system. 

![image](https://user-images.githubusercontent.com/3439710/28616429-58141de2-721a-11e7-807f-5c760e969a5a.png)

**Comment by gromo** [comment]
I believe you forgot to include jquery.scrollbar.css file, look [here](https://jsfiddle.net/Ld4qa4Lz/1/)

**Comment by warlockdn** [comment]
umm. that is weird. Not sure how I messed that up. Thanks. Silly me.
