### ISSUE TITLE
Invalid regular expression: /(^|\.)scrollbar_2(\.|$)/

### ISSUE THREAD

**Issue by ichsanwahyudi29** [gromo/jquery.scrollbar#149]
<img width="1432" alt="screen shot 2018-01-22 at 17 48 04" src="https://user-images.githubusercontent.com/32062159/35217065-7403f30a-ff9c-11e7-8de5-4389c62b3749.png">

When I "scroll" the scrollbar and then show that error, I use jquery 1.9, is have to use jquery 1.7? how if I want to use higher version of jquery?

thank you

**Comment by gromo** [comment]
Can you prepare example on jsFiddle.net ? This is the first time I see such error

**Comment by ichsanwahyudi29** [comment]
https://jsfiddle.net/Ichsanindraw/3cw3f8mk/6/?utm_source=website&utm_medium=embed&utm_campaign=3cw3f8mk

I try in jsFiddle but it's work, but I didn't know why when I try in my project it's didn't work, but if I use jquery 1.7.1 or higher version ( > 1.9.1 ) it's working

**Comment by gromo** [comment]
Hi. I think it may be jQuery bug. Fix is to change jQuery version :)
