### ISSUE TITLE
scrollbar not working with latest version of jquery 3.3.1 

### ISSUE THREAD

**Issue by ilianavaj** [gromo/jquery.scrollbar#153]
I was trying to update the jquery  library to the latest version - 3.3.1, as 1.7.1 has vulnerabilities issues. I noticed that scrollbar is now not showing at all. Is this possible to fix? Thanks!

**Comment by gromo** [comment]
@ilianavaj I've tested it with latest jQuery 3.3.1 and it works. Can you provide example of not working scrollbar on jsFiddle.net ?

**Comment by gromo** [comment]
@ilianavaj  I believe your comment has to be here about not-found class and null/undefined result
