### ISSUE TITLE
Update the jquery plugin repo

### ISSUE THREAD

**Issue by sateffen** [gromo/jquery.scrollbar#17]
Hey,

I've just found the bug you fixed in 0.2.5, and looked at your jquery plugin repo page [here](https://plugins.jquery.com/scrollbar/), because this is the point I downloaded the project from, and thought I have to fix it by my self, because there is no update. By chance I saw, that you released a new version, that fixed the bug (real thanks for that, saved me some hours) and want to ask you, whether you could update the jquery plugin repo page [https://plugins.jquery.com/scrollbar/](https://plugins.jquery.com/scrollbar/), so the people know there is a fix.

Thanks and good job!

**Comment by mvastola** [comment]
Fyi, this is resolved too.
http://bower.io/search/?q=jquery.scrollbar shows the package was updated 8 weeks ago (cooresponds with 0.2.6).

**Comment by sateffen** [comment]
It's updated on bower, yep, but not on jquery.com^^

https://plugins.jquery.com/scrollbar/ says the last version is 0.2.4, and got updated on 15.7.2014

**Comment by gromo** [comment]
I don't know why it is so. I've done everything according instructions, and it has worked before

**Comment by gromo** [comment]
Looks like hook/service does not work - all jquery plugins are not updated since last year
