### ISSUE TITLE
Scroll not rendering on OS X Firefox 

### ISSUE THREAD

**Issue by Sinled** [gromo/jquery.scrollbar#18]
```js
// do not init if in ignorable browser
if ((browser.mobile && o.ignoreMobile)
        || (browser.overlay && o.ignoreOverlay)
        || (browser.macosx && !browser.webkit) // still required to ignore nonWebKit browsers on Mac
        ) {
    return false;
}
```

из-за последней проверки ```browser.macosx && !browser.webkit```  кастомные скроллы не редерятся в невебкит браузерах, на Маке, например в Firefox и opera 12

**Comment by DenimTornado** [comment]
В моём случае скролл вообще пропадает при такой настройке.

**Comment by mvastola** [comment]
Hi,
Could someone translate this for english speakers? Which bug is this a duplicate of?
Mike

**Comment by gromo** [comment]
@mvastola look at this issue https://github.com/gromo/jquery.scrollbar/issues/12

**Comment by devoizo** [comment]
Возможное решение предложил @clexit в Diokuz/baron#91
> A bit hacky way would be to add something like "margin-right: -30px; padding-right: 30px;" to a scrollable container and then cut these 30px by setting "overflow: hidden" to a wrapper, so the native scrollbars will be hidden.

**Comment by evromalarkey** [comment]
Is the condition browser.macosx && !browser.webkit still needed? I've commented it and tested on two macosx devices and it works fine.

**Comment by gromo** [comment]
AFAIK it depends on OS settings, so it still needed
