### ISSUE TITLE
Scrollbar with max-height: 100%

### ISSUE THREAD

**Issue by julkue** [gromo/jquery.scrollbar#20]
Hello,

previously I used the perfectscrollbar but since it is not IE8 compatible I gave jquery.scrollbar a try. Unfortunately I have problems with it.
I have a overlay with a navigation. This navigation should be 100% height. Unfortunately:

```
                .scroll-wrapper{
                    max-height:100%;
                    height:auto;
                }
```

and also

```
                .scroll-wrapper{
                    height:100%;
                }
```

will not work.
@gromo What can I do to have a scrollbar with 100% height?

**Comment by julmot** [comment]
Well yes, you are right it is not a issue of the scrollbar. For all those who have the same problem: use `overflow:auto;` and do not initialize the plugin too see the default browser scrollbar. Than you will see what causes the problem!

Thanks for help!
