### ISSUE TITLE
Rails test (Minitest) throws error on css file

### ISSUE THREAD

**Issue by prodigerati** [gromo/jquery.scrollbar#22]
When I run controller tests using rails minitest I get the following error:

    ActionView::Template::Error: Invalid CSS after "...round: url(data": expected comma, was ":image/svg;base..."

I found the svg reference in the css jquery.scrollbar.css file:

     background:url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2ZlZmVmZSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNmNWY1ZjUiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);

Scrollbar displays correctly in chrome and safari.

**Comment by mvastola** [comment]
Please see Pull Request #25 . This is, in fact, a bug, and is easily fixed.

**Comment by mvastola** [comment]
I can verify that this is now fixed by #25 .

**Comment by prodigerati** [comment]
Thank you! Closing...
