### ISSUE TITLE
Problem with outer scrollbars

### ISSUE THREAD

**Issue by MatneX** [gromo/jquery.scrollbar#28]
Hi Gromo,
first of all, this is the BEST scrollbar for me. But there is a problem with 'scrollbar-outer' (maybe others, too). Your JS removes the margin right and at the bottom. Thats ok, but when you remove the margin, it would be nice to add it to the container, so that the design won't break. At the moment the boxes will have no margin between them.

**Comment by gromo** [comment]
Hi.
You should apply margin to your container by CSS class, not using style attribute, or I don't understand your question. Can you make an example of what you need on jsFiddle.net?

**Comment by MatneX** [comment]
Hi,

sorry can’t make an example at this moment.

But you can try it. I just createt 2 <pre> elements with with 100% and Bootstrap.

So the second pre will be unter the first. And Bootstrap has a CSS-Class for this element.

In the Class the element has margin-bottom:10px. Your Outer Scroolbar deletes the 10px and adds -17px.

That means, between both pre-boxes won’t be the 10px margin, they will be together, looking like one box with no space in between.

 

So if the scrollbar removes the margin from an element, it shoult add the same margin tot he scroll-container.

So the Scroll-Container should have a 10px margin (or what ever is given with css).

 

I could do this with my css and add f.e. a margin to all scroll-container, but  what if there are different margins, for different elements? It is more easy to do it in your script. Here an example:

 

Line 229 add:

                                                               if( cw.css("margin-bottom") || cw.css("margin-right") ) {

                                                                              cw.parent().wrap("<div class=\"scroll-container\" style=\"" +

                                                                                                                                             ((cw.css("margin-bottom"))?"margin-bottom:" + cw.css("margin-bottom") + ";":"") +

                                                                                                                                             ((cw.css("margin-right"))?"margin-right:" + cw.css("margin-right") + ";":"") +

                                                                                                                                             "\"></div>");

                                                               }

Regards,

Mathias

 

Von: Yuriy Khabarov [mailto:notifications@github.com] 
Gesendet: Freitag, 23. Januar 2015 09:44
An: gromo/jquery.scrollbar
Cc: MatneX
Betreff: Re: [jquery.scrollbar] Problem with outer scrollbars (#28)

 

Hi.
You should apply margin to your container by CSS class, not using style attribute, or I don't understand your question. Can you make an example of what you need on jsFiddle.net?

**Comment by gromo** [comment]
@MatneX please note that your container is wrapped into another one with the same classes + `scroll-wrapper`. Margin -17px is set to internal container, not the wrapper, so if you apply CSS styles by classname, all your styles will be applied for wrapper.

**Comment by MatneX** [comment]
The Problem is, is want to use it for a CMS System. So others may add only a Style-Attribute and no CSS-Class. So i need a way to work with CSS and Style-Attribute. :/

**Comment by gromo** [comment]
Got it.

Paste next code

    if(c.attr('style')){
        w.attr('style', c.attr('style')).css('position', c.css('position') == 'absolute' ? 'absolute' : 'relative');
    }
after

    if(!w){
        this.wrapper = w = $('<div>').addClass('scroll-wrapper').addClass(c.attr('class'))
        .css('position', c.css('position') == 'absolute' ? 'absolute' : 'relative')
        .insertBefore(c).append(c);

It should help with margins.

**Comment by MatneX** [comment]
Looks good :) First tests are positiv and it is working.
You sgould add this to the script. For me it is working on my first tests.
So thank you. You did a great job here.
