### ISSUE TITLE
scroll и maxScroll всегда равны 0

### ISSUE THREAD

**Issue by Evangeline-Rei** [gromo/jquery.scrollbar#31]
$content.closest(".elzScroll").scrollbar({onScroll: function(x, y) {console.log(y);console.log(x)}})

scroll и maxScroll всегда равняются нулю при любом движении. Из-за чего невозможно сделать например автоподгрузку контента по достижению скроллом нижней точки.

![1231111](https://cloud.githubusercontent.com/assets/6499222/6006035/557cb008-ab20-11e4-92d2-dfbb681a9405.jpg)

**Comment by gromo** [comment]
[Тут](http://gromo.github.io/jquery.scrollbar/demo/angular.html), вроде, работает. Можешь привести пример на jsFiddle.net ?
