### ISSUE TITLE
Why are certain browsers "ignorable"?

### ISSUE THREAD

**Issue by greghopkins** [gromo/jquery.scrollbar#33]
```js
        // do not init if in ignorable browser
        if ((browser.mobile && o.ignoreMobile)
          || (browser.overlay && o.ignoreOverlay)
          || (browser.macosx && !browser.webkit) // still required to ignore nonWebKit browsers on Mac
        ) {
          return false;
        }
```

Why are certain browsers being "ignored"? I'm after consistent scrollbars across at least the major browsers.

I've integrated your plugin into my application and I see that in Chrome on MacOS, the conditional above is evaluating to true and the plugin doesn't add the elements necessary to show the scrollbars. On IE on Windows, however, the conditional evaluates to false, allow the elements to be added.

For shiggles, I commented out the lines shown above and everything works find in both browsers.

I am missing something here? 

Thanks for the help.

**Comment by gromo** [comment]
Yep, you missed firefox on MacOS.

This behavior is my mistake - I've added new option `ignoreOverlay` and set its default value to `true`.  Set this option to `false` directly in plugin, in global options or in options when you init your scrollbars

**Comment by greghopkins** [comment]
That did the trick. I experimented with that, but I want to make sure I keep the design/spirit of the plugin in tact. Thanks!
