### ISSUE TITLE
scroll bar is not applying to div having display:none

### ISSUE THREAD

**Issue by rover886** [gromo/jquery.scrollbar#34]
I am facing one issue related to scroll bar.

My HTML structure is like :

    <div class="questiondiv scrollbar-outer">
       <div class='qdiv'>
       </div>
       <div class='qdiv'>
       </div>
       <div class='qdiv'>
       </div>
       <div class='qdiv'>
       </div>
    </div>

In an .js file on `document.ready()` I am calling `$('.scrollbar-outer').scrollbar();` and after that I am setting 'display:none' to some div having class 'qdiv'. at a time only one div having class 'qdiv' will be having 'display:block'.

Problem is, when page get loaded, at that time the 'qdiv' which is currently having `display:block` is come with Customizable Scrollbar but when I set display:block to other `qdiv` Customizable Scrollbar will not work (default scrollbar get active).

**Comment by gromo** [comment]
Can you prepare example of incorrect behavior on jsFiddle.net ?

**Comment by rover886** [comment]
I tried in jsFiddle as you said it's working fine there also I tried with creating an simple HTML page it's working there also. so I started digging why it's not working in my project, last night I come to know that because of an another JS and CSS scrolls are getting hide in another div.
