### ISSUE TITLE
Mozilla 35.0.1 - Native Horizontal 

### ISSUE THREAD

**Issue by KingKailas** [gromo/jquery.scrollbar#35]
in firefox browser , i'm getting two horizontal scrolls, native and normal scroll, 

Please let me know how to disable native one :)

**Comment by gromo** [comment]
I have tested FF 35.0.1 for Windows [here](http://gromo.github.io/jquery.scrollbar/demo/basic.html) - everything works fine if you make browser width < 800px. FF for Mac is not supported as its native scrollbars cannot be hidden without loosing functionality. 

Please, prepare example on jsFiddle.net so I can look at your problem.
