### ISSUE TITLE
Mac browsers

### ISSUE THREAD

**Issue by mcroba** [gromo/jquery.scrollbar#36]
Hi Gromo,

Thanks for this plugin, great one. I know that FF for Mac is not supported but the plugin doesn't work anymore for Chrome and Safari as well (on Mac).

here is my versions:
Chrome: Version 40.0.2214.115 (64-bit)
Safari: Version 8.0.3 (10600.3.18)

I haven't investigate yet but at least you are aware of that.

Best regards

Edit:
it's ignored because browser.overlay is true for Chrome and Safari now

**Comment by gromo** [comment]
Hello.

Try to set option ignoreOverlay to false

**Comment by mcroba** [comment]
It's what I have done.

Thanks
