### ISSUE TITLE
AngularJS directive hide scrollbar 

### ISSUE THREAD

**Issue by k0tkin** [gromo/jquery.scrollbar#37]
Hi,

AngularJS directive make my scroll bar invisible but all other functionality work fine just no scroll bar
Do i need to change something in css before using this directive?

**Comment by gromo** [comment]
Look at the [demo](http://gromo.github.io/jquery.scrollbar/demo/angular.html). Maybe you forgot CSS class or custom scrollbar styles? Can you make an example on jsFiddle.net ?

**Comment by k0tkin** [comment]
Thank you for answer and this great plugin
I added this 'scrollbar-inner' CSS style instead of 'scrollbar-dynamic' and everything is okay
