### ISSUE TITLE
what css in style.css is required?

### ISSUE THREAD

**Issue by morrow95** [gromo/jquery.scrollbar#39]
Been screwing around with this for waaay to long tonight wondering why the heck it doesn't work.  Either there is css styling in your style.css that is required or...

You have inline css in your demo pages, ../includes/style.css attached in the head, then there is the ../jquery.scrollbar.css which isn't referenced, but looks to contain the different 'types' all-in-one.  If you remove the style.css from the demo page nothing works so there must be something in there that is 'needed'.

I've put an extremely slimmed down version of the basic.html below... what needs to be done given this example for this to work properly?

```
<!DOCTYPE html>
<html>
    <head>
        <title>jQuery Scrollbar Demo</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="../jquery.scrollbar.css" rel="stylesheet" type="text/css"/>

    </head>
    <body>


        <div style="height:150px; width:75%;">
            <div class="scrollbar-inner">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a,
                    scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus.
                    Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel
                    hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue,
                    pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est. Etiam
                    sit amet lectus quis est congue mollis. Phasellus congue lacus eget neque. Phasellus ornare,
                    ante vitae consectetuer consequat, purus sapien ultricies dolor, et mollis pede metus eget
                    nisi. Praesent sodales velit quis augue. Cras suscipit, urna at aliquam rhoncus, urna quam
                    viverra nisi, in interdum massa nibh nec erat.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a,
                    scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus.
                    Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel
                    hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue,
                    pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est. Etiam
                    sit amet lectus quis est congue mollis. Phasellus congue lacus eget neque. Phasellus ornare,
                    ante vitae consectetuer consequat, purus sapien ultricies dolor, et mollis pede metus eget
                    nisi. Praesent sodales velit quis augue. Cras suscipit, urna at aliquam rhoncus, urna quam
                    viverra nisi, in interdum massa nibh nec erat.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a,
                    scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus.
                    Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel
                    hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue,
                    pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est. Etiam
                    sit amet lectus quis est congue mollis. Phasellus congue lacus eget neque. Phasellus ornare,
                    ante vitae consectetuer consequat, purus sapien ultricies dolor, et mollis pede metus eget
                    nisi. Praesent sodales velit quis augue. Cras suscipit, urna at aliquam rhoncus, urna quam
                    viverra nisi, in interdum massa nibh nec erat.
                </p>
            </div>
        </div>

        <script src="../includes/jquery.js" type="text/javascript"></script>
        <script src="../jquery.scrollbar.js"></script>

	    <script type="text/javascript">
	        jQuery(document).ready(function(){
	            jQuery('.scrollbar-inner').scrollbar();
	        });
	    </script>

    </body>
</html>
```

**Comment by gromo** [comment]
1. Remove external wrapper with inline styles
2. Set `height`/`max-height` for your container to see scrollbar because if you don't set `height`/`max-height` (in _px_ or _% of parent_), how can you see scrollbar? Browser tries to expand content to fill all available space and shows scrollbar in case if there is overflowed content

Look at [example](http://jsfiddle.net/7ehrktzx/) on jsFiddle.net

**Comment by morrow95** [comment]
Okay, with that example I see where I was going wrong.  My thought was scrollbar-inner would inherit the values of its parent container, but they always need to be defined even if that is 100%.  Also, I noticed you must define the width/height of inner-scrollbar in css... setting them inline will not work.  This is more or less what I was looking to do - http://jsfiddle.net/7ehrktzx/2/ - as my parent container changes by inline styles through js.  Setting the width explicitly for inner-scrollbar in css to 100% solves the issue.

**Comment by gromo** [comment]
The main idea is that you should use your own class for container that applies dimension restrictions to your container (don't forget about `overflow:auto`). And, in case if custom scrollbar is not applied, you will see native browser scrollbar. So the basic test if scrollbar should work - disable custom scrollbar initialization and check if you're able to see native one. I believe you don't need external wrapper with inline-styles for your container.

The classes defined in scrollbar CSS file are used to define scrollbar UI, so it's better to not use them for settings height/width restrictions. It will allow you easily change scrollbar look by changing class. Also different containers in your application have different sizes, so better to use different classes for them, and leave scrollbar's classes for defining UI-part only.
