### ISSUE TITLE
Не обновляется положение скролла в <textarea> при изменении текста

### ISSUE THREAD

**Issue by pix666** [gromo/jquery.scrollbar#43]
После ввода текста, скроллбар в нижнем положении, как и положено:

![17fa936f1f](https://cloud.githubusercontent.com/assets/6928240/7396166/9c92d97a-eea7-11e4-96ab-f14ef8348551.jpg)

Крутим колесико мыши вверх - никакой реакции. Однако, если прокрутить колесико мыши вниз, то нас перебросит к началу, как будто мы изначально находились вверху:

![f7aa0fa09f](https://cloud.githubusercontent.com/assets/6928240/7396170/a1a26d36-eea7-11e4-903c-c00c457b45bd.jpg)

**Comment by gromo** [comment]
Странное поведение. На странице [демо](http://gromo.github.io/jquery.scrollbar/demo/basic.html) такого поведения не наблюдается. Можно пример на jsFiddle.net ?

**Comment by pix666** [comment]
Вот пример: http://jsfiddle.net/og369gv9/
Поигравшись с настройками, я понял, что это из-за "disableBodyScroll: true"

**Comment by gromo** [comment]
Данная настройка была в моих подозрениях. В примере на jsfiddle есть зависания - реакция на скролл мыши происходит не сразу, однако скролл работает. Я советую не ставить эту опцию, а оставить стандартное поведение браузерного скролла.
