### ISSUE TITLE
Video won't play 

### ISSUE THREAD

**Issue by milosbelic** [gromo/jquery.scrollbar#46]
Your scrollbar helped me a lot on what I am trying to accomplish on my first website.The only issue is that my 'position: fixed' video at the bottom of the page won't play in any browser (I tried other position properties too).I hope you can help me, here is my website (sorry for free hosting ads) :

http://firstwebsite.comyr.com

Edit: It works in Firefox.

**Comment by gromo** [comment]
Hi @milosbelic 
I think it is problem of browser, not custom scrollbar you use - not all browsers support <video> tag + not all video formats are supported. To check it disable custom scrollbar and you will see that behavior remains the same.

Also, jQuery is included in your page twice, and second instance of jQuery overrides first one.

**Comment by milosbelic** [comment]
If you disable either one of these 3 scripts I downloaded from your site, the scrollbar lose its attributes and the video starts working.I am not learning Javascript yet, so I have no idea what is going on.


<--This is the js file from folder 'Includes'-->
<script type="text/javascript" src="js/jquery(includes).js"></script>

 <script type="text/javascript" src="js/jquery.scrollbar.min.js"></script>

 <script type="text/javascript">
         jQuery(document).ready(function($){
             window.prettyPrint && prettyPrint();
             $('.wrapper').scrollbar();
         });
  </script>
