### ISSUE TITLE
Empty space at bottom on dynamically removing table row

### ISSUE THREAD

**Issue by sandeepthomas** [gromo/jquery.scrollbar#50]
I have initialized jquery scrollbar on a table. table is having horizontal scroll only. I can add/remove rows dynamically on button click. On adding row there is no issue, however on removing rows, there is empty space at the bottom. 

Is there any solution?

**Comment by gromo** [comment]
Hi @sandeepthomas 
Can you prepare example on jsFiddle.net?

**Comment by sandeepthomas** [comment]
I tried to recreate the issue in jsFiddle using jquery, but was not able to do so.

My project is in angularjs. I will try to explain the issue to you.

In my project there is "scrollbar-outer, scroll-content, scroll-scrollx_visible" classes and some fixed height is directly applied by javascript to it. Where as in the JSFiddle, there are "scrollbar-inner scroll-content scroll-scrollx_visible" classes and no height. 

The inline height applied by javascript seems to be causing the issue. Any idea why it is there?

**Comment by sandeepthomas** [comment]
Ok, i have recreated the issue in jsFiddle. Please have a look

http://jsfiddle.net/f6y331db/2/

**Comment by gromo** [comment]
@sandeepthomas 

Thank you for your post. It is bug in custom scrollbar. I will try to fix it asap

**Comment by gromo** [comment]
Looks like it will take me few days to find out how to detect scrollHeight changes. Unfortunately I cannot get rid of 'height' for container - it's required to hide native scrollbar.

Fast hack in your case is handling changes in your models with scope.$watch and update scrollbar manually

**Comment by gromo** [comment]
I have a solution to use max-height instead of height, but it breaks custom scrollbars for textarea. If you do not plan using this plugin for textareas, I can send you modified version via email.

**Comment by sandeepthomas** [comment]
I don't plan on using this plugin for textareas. Please do send the modified version to the email which I sent you or post here.

Thanks

**Comment by gromo** [comment]
Hello.

I have updated scrollbar: fixed this bug + textarea support + js code refactoring. Please note that option `type` is removed, also CSS is changed
