### ISSUE TITLE
Not scrolling when sortable items get to edge.

### ISSUE THREAD

**Issue by joetidee** [gromo/jquery.scrollbar#52]
Hi, I am having an issue at the moment and struggling to find an answer. I am using Jquery UI Sortable inside a container that has the jquery.scrollbar plugin applied to it. When i drag an item to the bottom edge of the scroll area I would expect the scroll area to auto scroll - it doesn't. The list is structured like this:

```
<div class="scroll-area">
    <div class="list-container">
        <div class="list-item">Item 1</div>
        <div class="list-item">Item 1</div>
        ...
    </div>
</div>
```

with jquery.scrollbar applied to scroll-area. When i drag a list-item to the bottom edge of the scrolling scroll-area, then because the bottom edge of list-container is actually in the overflow, jquery.sortable cannot work inside the scroll-area container.

Do you have any suggestions to get around this?

**Comment by gromo** [comment]
Hi.

I know about problem with dragging relatively-positioned elements out of custom scroll area because of `overflow:hidden` applied to wrapper. But I haven't heard before about auto scrolling if drag element to the bottom edge of container. Can you disable custom scroll and check this behavior with native browser scrolls? If it works with native scrolls, then I need example on jsFiddle to see what happens

**Comment by joetidee** [comment]
ok, I found the issue which is not a bug in jquery.scrollbar, but just wondering if you can suggest a workaround....
Using the layout provided in my first post, the jquery sortable requires that the parent of the sortable elements (in this case list-container) have the overflow-y set to auto/scroll. Am i right that this cannot happen when using your plugin because your plugin must insist the scrollable contents to be wrapped in a containing div, hence the actual scrollable area becomes scroll-area?

**Comment by gromo** [comment]
Sorry for delay. Unfortunately I cannot suggest workaround until I see the problem. Can you make an example on jsFiddle.net ?

**Comment by DP-Prakash** [comment]
Try this
http://jsfiddle.net/aNh9H/615/
But this example is based on mcustomscrollbar.
Here too issue is due to overflow:hidden
