### ISSUE TITLE
Native scrollbar when toggling element

### ISSUE THREAD

**Issue by mfwonghk** [gromo/jquery.scrollbar#53]
Hi,

I have a sidebar menu with a submenu, which can be toggled by clicking the menu item.

http://jsfiddle.net/mfwonghk/8qu0j2p3/

In FF & IE, the native scrollbar is visible briefly after hiding the submenu. I can minimize the visible time by setting the update timeout to 0 but I think it is not a good idea.

**Comment by gromo** [comment]
Hi.

You are absolutely right - setting timeout to 0 will affect your performance. So, when you toggle your menu, just update scrollbar manually. Look at example http://jsfiddle.net/8qu0j2p3/4/

**Comment by mfwonghk** [comment]
What if I use sildeToggle? http://jsfiddle.net/mfwonghk/8qu0j2p3/5/

**Comment by gromo** [comment]
Use slideToggle progress callback: http://jsfiddle.net/8qu0j2p3/6/

**Comment by mfwonghk** [comment]
Thank you so much! Now I just need to implement that in my real sidebar...
