### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by Evangeline-Rei** [gromo/jquery.scrollbar#54]
В браузере Microsoft Edge (windows 10) виден стандартный скролл

**Comment by gromo** [comment]
Привет. А можешь прислать скриншот как он выглядит? У меня нет 10-ки, я сижу на 8.1 с ИЕ 11

**Comment by Evangeline-Rei** [comment]
Вот скриншот
http://pic.fullrest.ru/upl/EjE3SRrx.png

**Comment by gromo** [comment]
Спасибо, буду исправлять

**Comment by gromo** [comment]
Нашёл причину - это из-за UserAgent-а: в новой версии ишака они косят под все браузеры сразу: 
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240`, поэтому плагин думает, что это вебкит и обнуляет отступы, которые служат для сокрытия скроллбара. П*****сы.

Придётся искать другое решение для корректного детектирования браузеров.

**Comment by morrow95** [comment]
Just noticed the same thing when on a fresh upgrade to Win 10... scrollbars not displaying correctly in the new Edge browser.

Any word / updates on this?

**Comment by gromo** [comment]
@morrow95 
Edge browser developers are "smart": they lie about their browser - they use Apple Safari user agent instead of their own. I will fix it today-tomorrow

**Comment by gromo** [comment]
Wow, do you know that MS Edge browser not only lie in UserAgent, but also has same properties as real Webkit-based browser? I cannot use feature-based browser detection, so still use UserAgent, but filter Edge browser. Please, download updated version from site or beta version from git and re-check

**Comment by Evangeline-Rei** [comment]
Эдж вправился, а хром наоборот, сломался. Скрипт стал ставить маргины -17px соразмерные скроллу.

Впринципе, если закомментить скрывалку скролла в вебките, то всё становится нормально уже везде.
.scroll-content::-webkit-scrollbar {
    height: 0;
    width:  0;
}

Весь вопрос в том: есть ли смысл в сокрытии скроллбара на вебките путем цсса в таком случае?

**Comment by gromo** [comment]
Привет. Смысл быть просто обязан! :)
Надо будет завтра ещё раз перепроверить и запушить

**Comment by Evangeline-Rei** [comment]
http://gromo.github.io/jquery.scrollbar/demo/basic.html Точно. Здесь всё работает как надо. Я просто сунулся проверить на бете 0.3.0 https://github.com/gromo/jquery.scrollbar/blob/master/jquery.scrollbar.js, с этим скриптом не работает.

**Comment by gromo** [comment]
Ок, буду править.

@morrow95 
I have fixed custom scroll in version 0.2.8, which you can download from demo page. Beta 0.3.0 is not stable and not fixed yet.

**Comment by morrow95** [comment]
@gromo 
Working fine... thanks for the quick fix!  Any chance for a changelog page here on GitHub so we know what has been changed with this version?  I only mention because I tend to usually download from there.

Thanks again!

**Comment by gromo** [comment]
@morrow95 
Good idea, thanks.

**Comment by gromo** [comment]
@morrow95 
Changelog is added

**Comment by patrickkettner** [comment]
@gromo - were there any other issues keeping this open?

**Comment by gromo** [comment]
@patrickkettner  nope, just forgot to close

**Comment by patrickkettner** [comment]
:+1:
