### ISSUE TITLE
Scrollbar not showing when chidren's height set in %

### ISSUE THREAD

**Issue by sylvainjule** [gromo/jquery.scrollbar#57]
Hi,
I'm having some hard time trying to make the bar appear when used inside a list, 
with its li children's height set as 33.33333% (and 4+ li in a column).
The overflow isn't detected, the scrollbar doesn't show.
When set in px, no problem at all.

Here is a fiddle of the issue : 
http://jsfiddle.net/sylvainjule/zwL0pLng/4/

I currently get it working by previously formatting the height with jQuery : 
http://jsfiddle.net/sylvainjule/n3h01tvx/46/

But wonder if the issue has already shown up / there is a cleaner fix ?

**Comment by gromo** [comment]
Hi @sylvainjule 

This behavior is really strange and unexpected for me. I mark this as bug and will try to inspect and fix problem in next few days.

**Comment by gromo** [comment]
@sylvainjule 

Hi, sorry for delay. Unfortunately I am extremely busy these days and cannot look at this issue now, but I don't forget about it.

**Comment by sylvainjule** [comment]
No problem at all ! Thanks for looking into it.

**Comment by gromo** [comment]
I have reviewed your example. I'm afraid I cannot fix it. Unfortunately (I don't know why), children's height in % does not work if parent's height is set to `auto` (regardless of `min-height`/`max-height` values/actual element height), but I need `height:auto` because of negative margins that hides native browser scrollbars. So your hack/fix is the best possible option for now.

**Comment by arturparkhisenko** [comment]
@gromo i think same problem with flexbox layouts.. can you fix it?
related to % height https://github.com/malihu/malihu-custom-scrollbar-plugin/issues/68

**Comment by gromo** [comment]
@arturparkhisenko I will look at it in next few days

**Comment by gromo** [comment]
@arturparkhisenko 

jQuery scrollbar was easily applied to flexbox container. example on jsFiddle.net: http://jsfiddle.net/6Yrkr/19/ -

**Comment by arturparkhisenko** [comment]
@gromo thanks for check,i will show example later when i cant apply it ;( maybe its just rare case

**Comment by arturparkhisenko** [comment]
@gromo example: http://jsbin.com/guqivezejo/edit?html,output
before applying: all working fine and like it should be! (you can comment script and see that);
after applying plugin: scrollbar dissapears and padding of applied element is 0.

**Comment by gromo** [comment]
@arturparkhisenko What about CSS class for scrollbar?

**Comment by arturparkhisenko** [comment]
@gromo yep, my bad, forgot it :bulb: Thanks!

**Comment by arturparkhisenko** [comment]
@gromo Спасибо за OSS! :+1:  Merry Christmas, и с наступающим Новым Годом! :santa::christmas_tree::tada::snowboarder::ski::gift:
Потому что: https://twitter.com/cssunderhood/status/680383777516969985
