### ISSUE TITLE
AMD / Require JS Issue

### ISSUE THREAD

**Issue by jonathanamartin** [gromo/jquery.scrollbar#59]
I get the following exception when attempting to use Require JS:

```
Uncaught Error: Mismatched anonymous define() module: function ($) {
    'use strict';

    // init flags & variables
    var debug = false;

    var browser = {
        data: {
... continued...
```

If I add a module name to the define invocation, the exception goes away.

Old (line 16)
```javascript
 if (typeof define === 'function' && define.amd) {
        define(['jquery'], factory);
    } else {
```

New 
```javascript
 if (typeof define === 'function' && define.amd) {
        define('jquery-scrollbar', ['jquery'], factory);
    } else {
```

**Comment by gromo** [comment]
@jonathanamartin 

Any progress with this?

**Comment by jonathanamartin** [comment]
Yeah I think I'm good now.  We decided not to go with Require JS anyway.  According to the Require JS docs, I think we just had to load the file in a slightly different way. 

With that said, I think it's a non-issue.
