### ISSUE TITLE
Please update change log for version 0.2.6

### ISSUE THREAD

**Issue by ymaz** [gromo/jquery.scrollbar#60]
Hi, I've spotted that since version 0.2.6 the following default values have been changed to the 'true', instead of 'false': 'ignoreMobile' and 'ignoreOverlay'.

So, when I'm updated to latest version, i was really confused why everything has been stop working on mobile :)

So, please could you reflect those changes in your change log, maybe it may help someone else.

Many thanks.

**Comment by gromo** [comment]
Hi @ymaz 

Option ignoreOverlay was added in version 0.2.5, and ignoreMobile option default value was changed in version 0.2.1 - both these changes were mentioned in Changelog. And, thanks to you, I've updated changelog to note that both these options were changed to false by default in version 0.2.8

**Comment by ymaz** [comment]
Hi @gromo, thanks!:) Much appreciated.
