### ISSUE TITLE
Plugin does not check for overflow-x:hidden !important

### ISSUE THREAD

**Issue by julmot** [gromo/jquery.scrollbar#61]
Hello,

when styling the scrollbar-div with ``overflow-x:hidden !important`` the plugin does not register that it's not necessary to subtract the width of the scrollbar from the y-axis. So for example my scrollbar div is:
```html
<div class="scrollbar">...</div>
```
and my CSS is:
```css
.scrollbar{
  overflow-x:hidden !important
  width:100%;
  height:100%;
}
```
The plugin will still subtract the scrollbars width like (DOM Inspector):
```html
<div class="scrollbar" style="height: auto; margin-bottom: -17px; margin-right: -17px; max-height: 909px">...</div>
```
In this example the scrollbars width is 17px (Firefox).

I think this is a bug since the plugin should detect if the scrollbar is not shown and therefore not subtract if on the scrollbars div.

**Comment by gromo** [comment]
It's not easy to do, especially detecting CSS styles that are applied to container. I will think about option to hide horizontal scroll

**Comment by julmot** [comment]
If you initialize the scrollbar like e.g.
```html
<div class="my-scrollbar"></div>
```
the scrollbar-plugin will create a markup like
```html
<div class="my-scrollbar style="position:relative">
  <div class="my-scrollbar" style="height:auto; margin....">
   <!-- The content -->
  </div>
</div>
```
In my case because the plugin replicates the ``div.my-scrollbar`` it has the result that my second ``div.my-scrollbar`` does not have the ``height:100%`` I have defined in my CSS. Therefore the ugly browser scrollbar will appear, because the scrollbar-plugin will show it to calculate it's width/height.
This is the reason why I needed to use ```!important``. However because the scrollbar can not work with it, this is my current workaround:
```scss
&:not(.scroll-scrolly_visible){
	overflow-x:hidden !important; /* Fix scrollbar bug */
}
````

**Comment by gromo** [comment]
Do not hide scrollbar with !important. Instead update jquery.scrollbar.css styles to hide horizontal scrollbar and remove negative margin from container if horizontal scrollbar is visible

**Comment by julmot** [comment]
The problem is that the browser scrollbar will be shown if the content of the scrollbar-element is not height enough. This is why I had to add `overflow-x:hidden !important`. This occurs because the cloned scrollbar-element will have `height:auto;overflow:scroll !important;` applied (from the plugin). This is why the native scrollbar will appear.

How to hide it?

**Comment by gromo** [comment]
The quick solution is to use 2 containers - one for vertical scrollbar, and inner one with `width:100%` and `height:auto;` to hide horizontal scrollbar using `overflow-x:hidden`. Just apply custom scrollbar to external container - that's all.

**Comment by julmot** [comment]
@gromo Thanks for the reply. Do I understand you correctly (?):
```html
<div class="scrollbar-container">
    <div class="scrollbar" style="width:100%;height:auto;overflow-x:hidden;">
        <!-- this is the real scrollbar element -->
    </div>
</div>
```
I so, this styles will be automatically generated by the scrollbar plugin. And ``overflow-x:hidden;`` will be removed with ``scroll !important`` from the scrollbar styles css. Furthermore as I described above I can not enforce to remove the scrollbar with ``overflow-x:hidden !important`` since then the scrollbar will calculate the wrong max-height. So what would be the solution for this problem? And also, why does this happen?

**Comment by gromo** [comment]
Look at the example [here](http://jsfiddle.net/pyssvrjc/)
