### ISSUE TITLE
Provide onCancel event

### ISSUE THREAD

**Issue by julmot** [gromo/jquery.scrollbar#64]
When using "ignoreOverlay" or "ignoreMobile" the scrollbar will not beeing initialized. This is ok.
If you want to do something on scroll wou would normally use "onScroll". But this event will not get fired when the scrollbar is not beeing initialized. So you have to use the normal "scroll()"-event from jQuery.
I think this is not as intended... Also if you want to implement your own fallback the onCancel-event would be helpful.

**Comment by gromo** [comment]
You can always use standard jQuery `scroll` event with or without plugin initialized. I've added onScroll custom event for additional features, like % scrolled to know if container reached bottom. But same result is always possible using standard events as custom scrollbar is built on top of native browser scroll :)

**Comment by julmot** [comment]
Well, you can not use both the onScroll event and the native scroll event. This will cause performing issues because events will be called twice. Isn't it simple to set up the onCancel-event?

**Comment by gromo** [comment]
Nope. Use onInit event to handle scrollbar initialization and do whatever you want there.
