### ISSUE TITLE
Is there something wrong in the FAQ of the documentation?

### ISSUE THREAD

**Issue by Gpia** [gromo/jquery.scrollbar#66]
Question: How can I scroll content to position I need?

Answer: Use standard jQuery scrollTop/scrollLeft functions to the container. For example, you have container with class "scrollbar-macosx". Use next code to scroll 50px from top:

##  jQuery('.scrollbar-macosx').not('.scroll-content').scrollTop(50);    //this seems not effective

I tried this and then find the answer should be :

##  jQuery('.scrollbar-macosx.scroll-content').scrollTop(50);   //this seems ok.

Can someone make a answer to me ?

**Comment by gromo** [comment]
Sorry, it's mistyping. Use `jQuery('.scrollbar-macosx').not('.scroll-wrapper').scrollTop(50);` - it's safe option, event if custom scrollbar is not initialized. I believe that `jQuery('.scrollbar-macosx').scrollTop(50);` should work also, but `jQuery('.scrollbar-macosx.scroll-content').scrollTop(50); ` will work only if custom scrollbar was initialized

**Comment by gromo** [comment]
Thanks for report. I've updated documentation.
