### ISSUE TITLE
Question: How to debug issues with native scrollbars?

### ISSUE THREAD

**Issue by julmot** [gromo/jquery.scrollbar#68]
Hey,

I have a problem with the plugin in MS Edge:
![tmp](https://cloud.githubusercontent.com/assets/8310677/10583166/c7b18a9a-768b-11e5-9ef8-14c0a032fb93.png)
but I also had already problems in other browsers. However, this is my current problem. Of course I would like to fix the appearance of the native scrollbar. But how can I debug this? Unfortunately I am not able to reproduce it on jsfiddle. @gromo do you have any idea?

**Comment by gromo** [comment]
There are different ways to debug it. First of all, try to leave as less elements on the page as possible, ideally only scrollbar container should be on the page. Then try to inspect element and look at applied inline-styles (negative margins to hide native scrollbars). Custom scrollbar contains several steps, applied in `init` function: 

ROW NUMBER: COMMENT
141: // init variables
155: // do not init if in ignorable browser
163: // init scroll container
248: // init scrollbars & recalculate sizes
400: // remove classes & reset applied styles
410: // calculate init sizes
423: // update scrollbar visibility/dimensions
431: // calculate scroll size

As you can see from comments, each section has its own purpose. So try to see what happens on each step using `console.log`. Also, if you change JS code and do not want your browser hangs, enable debug mode or set option `autoUpdate:false` - it will prevent infinity scroll recalculation in case you update container/content size incorrectly.

**Comment by julmot** [comment]
It seems that the plugin does not calculate values for `margin-right` and `margin-bottom`, because they have the value `0px` applied in the DOM view:
`height:auto; right: 0px; margin-bottom: 0px; max-height: 650px`

**Comment by gromo** [comment]
Please, check that row 37 contains:

`webkit: /webkit/i.test(navigator.userAgent) && !/edge\/\d+/i.test(navigator.userAgent)`

**Comment by julmot** [comment]
It wasn't. After adding it the native scrollbar disappeared but also the custom scrollbar. So no scrollbar is visible now.

Is this regex update a beta feature?

**Comment by julmot** [comment]
I just updated the complete jquery.scrollbar.js file and now it works in MS Edge. That is great :+1: 

However, @gromo you need to add a new semver tag for this fix to allow bower users like me to use it in feature. This fix didn't came with a `$ bower update`!

**Comment by gromo** [comment]
Yep, unfortunately it's so - bower contains version without this fix

**Comment by julmot** [comment]
Ok, then could you please update the version?

**Comment by gromo** [comment]
OK

**Comment by gromo** [comment]
Done
