### ISSUE TITLE
Smooth body scroll on iOS devices

### ISSUE THREAD

**Issue by julmot** [gromo/jquery.scrollbar#69]
I am using the plugin as a body scrollbar in one project. 
```javascript
$scrollElement.scrollbar({
	ignoreOverlay: true,
	ignoreMobile: true,
	onInit: function(){
		$log.debug("Initializing scrollbar");
	}
});
```
As a parameter I've passed ``ignoreOverlay``. This will cause the native scroll behaviour to appear on e.g. an iPad device with iOS 8.4. This is just fine.

To make it work cross-browser it is necessary to pass ``height:100%`` to the body, that the scrollbar div inside the body tag can also have ``height:100%`` applied.
```css
body{
	position:absolute;
	top:0;
	left:0;
	width:100%;
	height:100%;
	overflow:hidden;
}
```
This works in all Desktop browsers. However, on an iPad 3 with iOS the scroll behaviour is very buggy. It seems to be that Safari can only handle the body itself as a main scrollbar element. Because the "minimal ui" toolbar will never appear. Also the scroll is not smoothly and the native scrollbar will also not appear. You can test it on the plugin homepage itself: http://gromo.github.io/jquery.scrollbar/

The issue would be fixed when using ``height:auto`` on the body-element. However this would make the plugin unusable on Desktop browsers. However, in my opinion it is not a workaround to detect the iOS Safari browser and then set ``height:auto`` to the body. This is against "feature detection" and should be done in a way that is not "hacky". @gromo What do you think?

**Comment by gromo** [comment]
Hi @julmot 

Use function `onInit` to apply class to body in desktop browsers. This function is run only if plugin is initialized, and won't run on mobile/tablets

**Comment by julmot** [comment]
Yes, but imho this would be just a workaround. Or do you think this is the permanent solution for it?

**Comment by gromo** [comment]
Permanent. Custom scrollbar originally is not designed to replace body scrollbar, so it's best option.

**Comment by julmot** [comment]
I'm afraid...
