### ISSUE TITLE
set height from style

### ISSUE THREAD

**Issue by clarkk** [gromo/jquery.scrollbar#71]
How to set the height with style/javascript

```
<div class="scrollbar-inner">
    test<br>test<br>test<br>test<br>test<br>
    test<br>test<br>test<br>test<br>test<br>
    test<br>test<br>test<br>test<br>test<br>
    test<br>test<br>test<br>test<br>test<br>
</div>

$('.scrollbar-inner').css('height', 300).scrollbar();
```

**Comment by gromo** [comment]
Use CSS class with `height` or `max-height`. If you want to limit height via inline styles/javascript, add class to your container with `height:100%` and wrap it with DIV, where you can set height with inline styles.

**Comment by clarkk** [comment]
ok.. thats a goog solution

**Comment by clarkk** [comment]
How is it then possible to "activate" the horizontal scrollbar?

```
elm.scrollbar({
    scrolly : 'simple'
});
```

There are no examples in the documentation which is covering some simple use cases

**Comment by gromo** [comment]
http://gromo.github.io/jquery.scrollbar/demo/basic.html

> Basic Scrollbars
> Resize window to 600px width to see horizontal scrollbar

**Comment by clarkk** [comment]
https://www.dropbox.com/l/s/kelfug6n9tv9fUbYzbdpKs
