### ISSUE TITLE
Not working in Firefox on Apple

### ISSUE THREAD

**Issue by clarkk** [gromo/jquery.scrollbar#72]
You can't set the height this way on Apple..

Works fine on Windows with Firefox, Chrome and IE

```
.scrollbar_content {
    height:100%;
}

<div id="scrollbar_id" class="scrollbar_content scrollbar-inner"></div>

$('#scrollbar_id').scrollbar();
```

**Comment by gromo** [comment]
Apple: Mac, iPhone, iPad? What version of browser?
Please, prepare example on jsFiddle.net for me to see the problem.

**Comment by clarkk** [comment]
http://jsfiddle.net/d99d5jzw/2/

I can't add resources from github

**Comment by gromo** [comment]
Safari console output:

Did not parse stylesheet at 'https://raw.githubusercontent.com/gromo/jquery.scrollbar/master/jquery.scrollbar.css' because non CSS MIME types are not allowed in strict mode.

Also, do not forget about overflow:auto property. Although jquery plugin works without it, you won't see native scrollbar without plugin CSS

Fixed version: http://jsfiddle.net/d99d5jzw/4/

**Comment by clarkk** [comment]
I dont want the native scrollbar but the simple scrollbar defined in css

**Comment by gromo** [comment]
I see custom scrollbar in provided example, both yours and mine

**Comment by gromo** [comment]
Btw, Firefox under Mac is ignored as there is no way to hide native scrollbar

**Comment by clarkk** [comment]
I'll get back to you.. I don't have mac, so I need print screens etc from someone first..

**Comment by clarkk** [comment]
Hi gromo..

Have now connected to a guy with teamviewer so I could test it myself..

It seems to work fine in both Safari and Chrome on Mac though.. But in Firefox version 42.0 its not working

![ff42](https://cloud.githubusercontent.com/assets/1913916/11714245/1365e71c-9f39-11e5-9521-9b0eec90d122.png)

**Comment by gromo** [comment]
Look at my comment above - this plugin does not work with FF on Mac. Also there is bug #12 with status 'Won't fix' below - there is no way to hide native scrollbar, so plugin just not initialized and you should see native scrollbars

**Comment by clarkk** [comment]
But no native scrollbars is shown with FF on Mac? There is no failover

**Comment by gromo** [comment]
@clarkk because you didn't set `overflow: auto;` in CSS for .scrollbar_content

**Comment by clarkk** [comment]
great.. now it works :)

**Comment by ntnwrd** [comment]
@gromo Thanks for building this and helping with issues. Can I request that you please update readme.md to reflect browser support ("this plugin does not work with FF on Mac"). Thanks
