### ISSUE TITLE
Angular JS Directive Fails when Minified

### ISSUE THREAD

**Issue by mpetito** [gromo/jquery.scrollbar#73]
The angularjs directive needs to supply its argument names as strings for ioc, otherwise ioc will fail when the arguments are minified.

I would put together a pull request but the change is quite simple to the `jqueryScrollbar` directive:

    ["jQueryScrollbar", "$parse", function (jQueryScrollbar, $parse) {
    ....

**Comment by gromo** [comment]
@mpetito 

I have updated minified version (because original version contains directive dependencies in a correct way) and pushed to repository, but I didn't update version, so bower contains and last release contains minified version without this change.

**Comment by tunurgitr** [comment]
@gromo +1 to @mpetito as my build process references the javascript file indicated in bower.json, which is the "unminified" version.  It's awkward to have the normal JS file not be "minification-safe".  

Everything else I use *is* min-safe.

My alternative is to form this repository...which I'd rather avoid.

**Comment by gromo** [comment]
Version increased to update bower repository
