### ISSUE TITLE
error showing in firefox - not sure what it is or does

### ISSUE THREAD

**Issue by morrow95** [gromo/jquery.scrollbar#74]
I just noticed this error showing rather consistently and not quite sure what is happening.  Appearance and functionality wise everything looks and works fine though.  In firebug under firefox I am showing this : 

```
TypeError: o is undefined
i</<()
u = undefined

...rollx,a=f.scrolly,(u||c.autoUpdate&&e&&e.is(":visible")&&(o.prop("scrollWidth")!...
```
the firebug arrow points to the period in 'e.is' in the above line.  Anyone?  I am using a minified js file.

**Comment by gromo** [comment]
Sorry for delay, could not find time to review issues. Can you prepare example on jsFiddle.net?
