### ISSUE TITLE
How add easing to scroll content

### ISSUE THREAD

**Issue by bojanbb** [gromo/jquery.scrollbar#75]
Hi, 

I have a question - How add easing (http://gsgd.co.uk/sandbox/jquery/easing/) to scroll content?

Thanks in advance

**Comment by gromo** [comment]
Hi @bojanbb 

There are 2 types of scrollbar plugins: ones that uses native browser scroll and the ones that emulates it. jQuery.scrollbar plugin is the first type of plugins, so easing cannot be added. Use one of the plugins of the second type. Look at this sheet (although it's a little bit old, but still can be used for information): https://drive.google.com/open?id=1sjb7nGrTtflPNtPRkL6fryUEaT4Ls0CrGrpMiAl3YQw - look at the Type:emulator.
