### ISSUE TITLE
disableBodyScroll

### ISSUE THREAD

**Issue by s0By** [gromo/jquery.scrollbar#78]
Trying to apply disableBodyScroll but then I'm having this issue that the scroll in the container (not page) starts flickering if I start at the very top or the very bottom. If I drag the scrollbar it works normally, if I scroll slowly (like super slowly) it works normal as well, but if I do a usual 2 finger (trackpad on mac) fast scrolling then it's flickering for a second and then scrolls normally after that.

But behaviour is not normal and annoys a lot. 

Any way to prevent that?

**Comment by gromo** [comment]
AFAIK trackpad generates ten times more 'scroll' events, so it overloads JS engine and redrawing process happens too many times which causes flickering. I don't know yet what to do in this case.

It's better not to use this option if possible - use native scrolling as this plugin was designed to do :)

**Comment by s0By** [comment]
Do you know any hacks that I could use to disable page scrolling at the moment?
I have a notification window, something similar to the one that Facebook has and wanted to achieve the same behavior as they do. Like the page scroll would stay but wouldn't work until i'm inside the other container. 

The only hack that I was able to achieve is to hide the scroll of the page while notification container is open, but that's not an ideal approach.

**Comment by gromo** [comment]
All popups I know use 2 common ways:
1. overlay that blocks accessing background page, scrolling available
2. disable page scrolling

I prefer the second way - it allows popup always be in the center of window.

The third way is to handle mousewheel/drag events manually and prevent default actions. But it's not worth the efforts
