### ISSUE TITLE
scrollbar divs not getting generated in MAC

### ISSUE THREAD

**Issue by AravindKrishnamoorthy** [gromo/jquery.scrollbar#81]
Hi,

We have been using JQuery.scrollbar plugin in our project for quite a while. We are using the version 0.2.5in our project.

The plugin is not generating the supporting scrollbars div in the browsers on MacOS (10.11.x). The divs with the styles viz., "scroll-x scroll-scrollx_visible scroll-scrolly_visible" and "scroll-y scroll-scrollx_visible scroll-scrolly_visible" are not getting generated in MacOS. Because of which there is no scrollbar visible in the MacOS devices.

When we manually code these divs the scrollbars appear, but not movable. Introducing the "scrollbar-macosx" from your demo page in our stylesheets and using it for the wrapper div, gets this scrollbar useable. This is the case only on MacOS (scrollbar is not appearing only in Chrome 48 on Mac OSX 10.11.x). 

Is there any known bug related to this or was the scrollbar designed to not generate these divs on MacOS ? 

Thanks,
Aravind

**Comment by gromo** [comment]
Hi Aravind.

jQuery Scrollbar is not initialized on Mac for non-webkit browsers (Firefox, for example). If it's not initializing for webkit-based browsers (Chrome, Safari), check that option `ignoreOverlay` is set to `false` (this option was added in version 0.2.5 with default value `true`, but in version 0.2.8 default value was changed to `false`).

**Comment by AravindKrishnamoorthy** [comment]
Thank you for your response.

I did try that earlier looking at your responses for previous queries. That does not seem to work for us.

**Comment by gromo** [comment]
Can you check if custom scrollbar is visible on Mac here: http://gromo.github.io/jquery.scrollbar/demo/basic.html ?
