### ISSUE TITLE
Not scrolling when sortable items get to edge

### ISSUE THREAD

**Issue by DP-Prakash** [gromo/jquery.scrollbar#85]
Refer issue #52 
When we drag an item to the edge, auto scroll is not happening.
But when browser default scrollbar is used autoscroll works
Try this fiddle
http://jsfiddle.net/aNh9H/615/
But this example is based on mcustomscrollbar.
Here i found the issue is due to overflow:hidden

**Comment by gromo** [comment]
Unfortunately I have to use overflow:hidden in order to hide native scrollbars
