### ISSUE TITLE
Need an callback if scrollbar is not initialized (MacOS Firefox)

### ISSUE THREAD

**Issue by Dineshkanin** [gromo/jquery.scrollbar#87]
Its very helpful if you give a callback method if scrollbar not initialized.

`if ((browser.mobile && o.ignoreMobile)
                || (browser.overlay && o.ignoreOverlay)
                || (browser.macosx && !browser.webkit) // still required to ignore nonWebKit browsers on Mac
                ) {
            	**Callback in here**
                return false;
            }`

**Comment by gromo** [comment]
Good idea. I will call it onFallback and implement in next few days

**Comment by Dineshkanin** [comment]
Thank :)
