### ISSUE TITLE
jquery1.12.3 does work!

### ISSUE THREAD

**Issue by gggin** [gromo/jquery.scrollbar#88]
$(xxx).scrollbar() no this funciton

**Comment by gromo** [comment]
Please check that you have only 1 version of jQuery on your page and Scrollbar plugin included after jQuery. Also, check if there are javascript errors in browser console

**Comment by gggin** [comment]
![image](https://cloud.githubusercontent.com/assets/3293064/14417920/e4f8da00-ffec-11e5-996e-8c6645018451.png)
just easy use in this way and $('.scrollbar-inner').scrollbar is undefined

**Comment by gggin** [comment]
I found that jquery.scrollbar need v2.2.3 so there is two jquery... shit..
