### ISSUE TITLE
Using Scrollbar with Bootstrap, .row causes horizontal scrollbar x

### ISSUE THREAD

**Issue by danvim** [gromo/jquery.scrollbar#89]
I'm using Scrollbar with Bootstrap, `.row` causes horizontal scrollbar x because of it's CSS `margin: 0 -15px`. This is supposed to be used with `.col-xx-xx` to hide left and right margins of responsive column.

How can I do overflow x hidden using JS and not just hide the scrollbar for visual effects?

Here's a jsfiddle: https://jsfiddle.net/danvim/9g4fhrtk/

**Comment by gromo** [comment]
Try to put your content inside another container wrapped with .col-xx-x

**Comment by danvim** [comment]
@gromo But if I do this: https://jsfiddle.net/danvim/9g4fhrtk/2/ It defeats the purpose of leaving no space on the left and right. :/

**Comment by gromo** [comment]
Can you make an example without custom scrollbar - using standard browser one?

**Comment by danvim** [comment]
https://jsfiddle.net/danvim/9g4fhrtk/3/

Well, it seems like I was mistaken, sorry. I must have changed something else too when I went to use your custom scrollbar.

:pray:
