### ISSUE TITLE
horizontal scroll

### ISSUE THREAD

**Issue by clarkk** [gromo/jquery.scrollbar#94]
How to add a horizontal scrollbar?

```
<div style="height:55px; width:200px">
  <div class="scrollbar_content scrollbar-inner">
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
  </div>
</div>

.scrollbar_content {
	height:100%;
	overflow:auto;
}

.box {
  display:inline-block;
  margin:2px;
  background:red;
  height:50px;
  width:50px;
}

$('.scrollbar_content').scrollbar();
```

http://jsfiddle.net/s5ng001z/10/

**Comment by gromo** [comment]
What about CSS styles? What about native horizontal scrollbar without custom plugin?

**Comment by clarkk** [comment]
Forgot CSS styles.. Added..

Put how to remove vertical scroll and only use horizontal?

http://jsfiddle.net/s5ng001z/11/

**Comment by gromo** [comment]
How would you do it without custom plugin? Try to get native horizontal scrollbar, and then apply custom scrollbar

**Comment by clarkk** [comment]
have tried here
http://jsfiddle.net/s5ng001z/12/

**Comment by gromo** [comment]
doesn't work. Something is wrong with your HTML/CSS. Disable custom plugin initialization and try to get browser's horizontal scrollbar
