### ISSUE TITLE
scroll-bar top does not update

### ISSUE THREAD

**Issue by daniel-rabe** [gromo/jquery.scrollbar#98]
when the height of the children is smaller then max-size the position of the ".scroll-bar" element does not update, it stays on the position from before the size-change.

we use jquery.scrollbar in our react app; on componentUpdate we call this:

public updateScrollbar(pElement: Element, pClass: string, scrollTop: boolean = false) {
let scrollDiv = $(pElement).find('.scrollbar-wcf');
scrollDiv.scrollbar({
ignoreOverlay: true,
ignoreMobile: true
});

if (scrollTop && pClass) {
$(pElement).find(pClass).scrollTop(0);
}

even if scrollTop(0) is called the position of scroll-bar is not updated (style="top: xxx")
so we need to manually overwrite the style by:

$(pClass.toString() + ".scrollbar-wcf > div.scroll-element.scroll-y > div > div.scroll-bar").css("top", "0");

**Comment by gromo** [comment]
try next: 

$(pElement).find(pClass).scrollTop(0).trigger('scroll')

**Comment by daniel-rabe** [comment]
thanks, but this also does not work :(

**Comment by gromo** [comment]
if you can prepare example on jsFiddle, I can look at it
